[rust]
debuginfo-level = 1

[package]
name = "gameboy-emulator"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = 1

[dependencies]
clap = { version = "4.3.0", features = ["derive"] }
sdl2 = { version = "0.35.2" }
